### ISSUE TITLE
AWS Lambda error

### ISSUE THREAD

**Issue by miguelwebtales** [gios/gzipper#103]
I am getting a error on running the code sample bellow on AWS lambda with node version 16. On local it's ok.

The gzipper version is the 7.2.0

```
const { Compress } = require('gzipper');
const gzip = new Compress('./src', './dist', {
  verbose: true,
  brotli: true,
  deflate: true,
});

try {
  const files = await gzip.run();
  console.info('Compressed files: ', files);
} catch (err) {
  console.error(err);
}
```

Error logs:

```
Error: Initiated Worker with invalid execArgv flags: --expose-gc, --max-semi-space-size=102, --max-old-space-size=1844
    at Compress.<anonymous> (/var/task/node_modules/gzipper/src/Compress.js:184:31)
    at step (/var/task/node_modules/gzipper/src/Compress.js:44:23)
    at Object.throw (/var/task/node_modules/gzipper/src/Compress.js:25:53)
    at rejected (/var/task/node_modules/gzipper/src/Compress.js:17:65)
```

**Comment by gios** [comment]
Hi @miguelwebtales , did you set some Node CLI arguments (`execArgv`) when you run gzipper?
