### ISSUE TITLE
Update 6.1.0 is a breaking change due to `node-zopfli`

### ISSUE THREAD

**Issue by demurgos** [gios/gzipper#92]
The recent 6.1.0 update added a dependency on `node-zopfli`. This is a native dependency that broke my builds because it adds new build-time requirements. Here are the logs:

<details>
<summary>See logs</summary>

```
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc=musl platform=linux)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR prebuild-install WARN install No prebuilt binaries found (target=14.18.1 runtime=node arch=x64 libc=musl platform=linux)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp info it worked if it ends with ok
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp info using node-gyp@8.4.1
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp info using node@14.18.1 | linux | x64
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python 
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python Python is not set from command line or npm configuration
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python Python is not set from environment variable PYTHON
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python checking if "python3" can be used
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python - "python3" is not in PATH or produced an error
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python checking if "python" can be used
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python - "python" is not in PATH or produced an error
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python 
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python **********************************************************
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python You need to install the latest version of Python.
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python you can try one of the following options:
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python   (accepted by both node-gyp and npm)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python - Set the environment variable PYTHON
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python - Set the npm configuration variable python:
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python For more information consult the documentation at:
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python **********************************************************
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! find Python 
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! configure error 
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack Error: Could not find any Python installation to use
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at PythonFinder.fail (/builds/demurgos/etwin/node_modules/node-gyp/lib/find-python.js:330:47)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at PythonFinder.runChecks (/builds/demurgos/etwin/node_modules/node-gyp/lib/find-python.js:159:21)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at PythonFinder.<anonymous> (/builds/demurgos/etwin/node_modules/node-gyp/lib/find-python.js:202:16)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at PythonFinder.execFileCallback (/builds/demurgos/etwin/node_modules/node-gyp/lib/find-python.js:294:16)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at exithandler (child_process.js:390:5)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! System Linux 5.4.109+
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! command "/usr/bin/node" "/builds/demurgos/etwin/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! cwd /builds/demurgos/etwin/node_modules/node-zopfli
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! node -v v14.18.1
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! node-gyp -v v8.4.1
➤ YN0000: │ node-zopfli@npm:2.1.4 STDERR gyp ERR! not ok 
➤ YN0009: │ node-zopfli@npm:2.1.4 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-18adf4dd/build.log)
```

</details>

I will try to fix my build environment, but you should be aware of the issue. I am not quite sure what can be done on the `gzipper` side. It seems a bit too late to release a `7.x` version as the consumers using `^6.x.y` are already affected. The best solution would be to use a pure node `zopfli` implementation.

**Comment by gios** [comment]
I'll take a look at this issue and find out which module we can use to avoid this prerequisite python. Currently, the only available module is [@gfx/zopfli](https://www.npmjs.com/package/@gfx/zopfli) with WebAssembly.

**Comment by demurgos** [comment]
Thank you for your quick reply, all active LTS Node versions support WebAssembly so it may be a good solution. :)

**Comment by Jalgoczy** [comment]
Had the same problem yesterday when updating our app. I would be grateful if you could resolve the issue so that we don't need to reconfigure our build-servers (to many changes have to be made, complicated) .
Thanks.

**Comment by gios** [comment]
I've deployed a new version v.7.0.0 with @gfx/zopfli module, check your CI's with the new version.
